# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_ingestion.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'data_ingestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x61ta_ingestion.proto\x12\x0e\x64\x61ta_ingestion\"T\n\x04Tick\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0b\n\x03\x62id\x18\x02 \x01(\x01\x12\x0b\n\x03\x61sk\x18\x03 \x01(\x01\x12\x0c\n\x04last\x18\x04 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"#\n\x10SubscribeRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\"/\n\x08Snapshot\x12#\n\x05ticks\x18\x01 \x03(\x0b\x32\x14.data_ingestion.Tick\"q\n\x10MarketDataUpdate\x12,\n\x08snapshot\x18\x01 \x01(\x0b\x32\x18.data_ingestion.SnapshotH\x00\x12$\n\x04tick\x18\x02 \x01(\x0b\x32\x14.data_ingestion.TickH\x00\x42\t\n\x07payload2b\n\rDataIngestion\x12Q\n\tSubscribe\x12 .data_ingestion.SubscribeRequest\x1a .data_ingestion.MarketDataUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_ingestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICK']._serialized_start=40
  _globals['_TICK']._serialized_end=124
  _globals['_SUBSCRIBEREQUEST']._serialized_start=126
  _globals['_SUBSCRIBEREQUEST']._serialized_end=161
  _globals['_SNAPSHOT']._serialized_start=163
  _globals['_SNAPSHOT']._serialized_end=210
  _globals['_MARKETDATAUPDATE']._serialized_start=212
  _globals['_MARKETDATAUPDATE']._serialized_end=325
  _globals['_DATAINGESTION']._serialized_start=327
  _globals['_DATAINGESTION']._serialized_end=425
# @@protoc_insertion_point(module_scope)
